### ISSUE TITLE
no network cennectify

### ISSUE THREAD

**Issue by BramRausch** [zhuowei/Xenologer#19]
Hello,

I have download the apks but if I will get directions or google it's says no network cennectify.
Can anyone help me?

I am connect to wifi.

bye

P.S. sorry for my bad english.

**Comment by ChristianFJung** [comment]
I have the same problem

Sent from my Virgin Mobile Android-Powered Device

----- Reply message -----

**Comment by zhuowei** [comment]
Will fix (by removing the no connectivity alert)

**Comment by zhuowei** [comment]
Try the updated version of Glass Home.
