### ISSUE TITLE
"Tap" not working

### ISSUE THREAD

**Issue by ayr-ton** [zhuowei/Xenologer#2]
Using a Nexus 7 with Android 4.2.2 and a Asus TF101 with the same android, it not possible to use the "tap" functions of glass apps.
For exemple, if I say something wrong it responds "tap to try again". I touched in all the places of the screen but nothing happens.

**Comment by ChristianFJung** [comment]
I got the same problem , but I would hit the button on my phone(back button) and that would work sometime , I think that is android taking over.

**Comment by zhuowei** [comment]
Tap to try again never works; in other places, use Enter key and arrows.

**Comment by limhenry** [comment]
where is the "Enter" key and the "arrow" key?

**Comment by zhuowei** [comment]
If you have a Bluetooth keyboard, connect it and use its keys; otherwise, I heard from Reddit that there's a WiFi keyboard available that allows you to use a PC as a keyboard: https://play.google.com/store/apps/details?id=com.volosyukivan

**Comment by jdstaerk** [comment]
Yes, it doesn't work for me too. With a wifi Keyboard it is working!

**Comment by ayr-ton** [comment]
@zhuowei @DDerTyp With the dock keyboard of TF101 the arrow keys and enter also worked.

**Comment by jdstaerk** [comment]
@ayr-ton okay! Thank you for this information.

**Comment by zhuowei** [comment]
@simonratner fixed it with his touchscreen modification.
