### ISSUE TITLE
Wrote a little app to navigate using volume and menu/back buttons

### ISSUE THREAD

**Issue by Androguide** [zhuowei/Xenologer#20]
I find the need to use an external/wifi keyboard was pretty annoying, so I wrote a simple InputMethodService app which allows the use of volume buttons to swipe left & right, and the menu button or long-pressed back button to simulate the enter key.

The app is open-source, you can grab the code on my github : https://github.com/Androguide/GLASSInput

The signed apk is there, too : https://github.com/Androguide/GLASSInput/blob/master/GlassInput.apk?raw=true

I'm working on making touch actually work by using a transparent layout for the "keyboard" and listen to tap & swipes on it to inject the right key press in function.

**Comment by zhuowei** [comment]
Nice! I'll link to that on the main page.

**Comment by Androguide** [comment]
Thanks @zhuowei :)

**Comment by BramRausch** [comment]
cool

**Comment by Novo** [comment]
thank you.

**Comment by zhuowei** [comment]
@simonratner unlocked touchscreen input, so closing this.
