### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by utkut** [zhuowei/Xenologer#27]
The app writes failed to create account rebooting deletes google accont and force closes help please

Android 4.0.3 HTC One V

**Comment by zhuowei** [comment]
I know, and I'll replace the stock setup application completely this week.

**Comment by utkut** [comment]
Are you going to add Facebook or Twitter support

iPod’umdan gönderildi

28 Haz 2013 tarihinde 23:54 saatinde, "zhuowei" notifications@github.com şunları yazdı:

**Comment by zhuowei** [comment]
Since this is just a port of the actual Google Glass software, you can just add the Facebook or Twitter Glassware from MyGlass once Setup works.

**Comment by utkut** [comment]
İs there any apps for control music

iPod’umdan gönderildi

29 Haz 2013 tarihinde 03:51 saatinde, "zhuowei" notifications@github.com şunları yazdı:

**Comment by zhuowei** [comment]
I'm only working on modifying Glass software to run, but I believe that, once we get setup working, you can look for Glassware to do that.
