### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by ToruHironaka** [zhuowei/Xenologer#38]
Hi, 

I installed your all apks on README.md file and everything seems to work right. I now try to install a sample program from Android Development Tools, but I cannot Turn on Debug (On Glass Home, Setting --> Device Info --> Turn on Debug). It always shows the message "Unfortunately, Glass Home has stoppred". Is it possible for me to Turn on Debug? or I just cannot turn it on with Glass Home. Please help.

**Comment by zhuowei** [comment]
Since Xenologer runs as a standard application, use the normal settings application on your device to turn on debug, not Glass settings.
Also, these APKs are really old; I'll be updating these when the next version of the Glass firmware is released.

**Comment by ToruHironaka** [comment]
Thanks for your quick response, I try it.
