### ISSUE TITLE
Cannot set up *PLEASE HELP*

### ISSUE THREAD

**Issue by Relexs** [zhuowei/Xenologer#5]
@zhuowei Hello, I don't see anything that tells me how to set this up. I have everything on my phone (Nexus 4 Android 4.2.2) and I still cannot go to www.google.com/myglass and be able to put in contacts or anything. When I run the setup (By pressing home then glass setup 'Just Once' it wont scan the QRcode on www.google.com/myglass setup or anything.

**Comment by ChristianFJung** [comment]
Hey you do everything right but you don't scan the qr code . You need a bluetooth keyboard and you just hit enter. (Make sure you have 1 google account on your phone, that is what it registers on)  Check out this vid

http://www.youtube.com/watch?v=fNsu9xvpdNw

It is really cool, btw I introduced him to this project

**Comment by Relexs** [comment]
Thank you. I will use my laser keyboard lol. Thanks sooooooo much again btw.

**Comment by ChristianFJung** [comment]
You have a laser one? Do they really work?

Christian Jung
