### ISSUE TITLE
Keyboard Problem

### ISSUE THREAD

**Issue by limhenry** [zhuowei/Xenologer#7]
Hi.
I'm now using a android 4.0 phone.
when i run the "glass set-up", but i don't have a Bluetooth keyboard. so, how should i do to continue to using the glass on my android phone?

**Comment by Relexs** [comment]
I used Hacker's Keyboard. There is a setting 'use permanent notification'. so you go to the right icon ( the two boxes to change screens on android) swipe down. click the notificaton. then go back to the glass app

**Comment by limhenry** [comment]
thanks ~ ^^

**Comment by zhuowei** [comment]
Most people use a Wi-Fi keyboard app actually. I tried Hacker Keyboard, but it keeps disappearing on me. :(

https://play.google.com/store/apps/details?id=com.volosyukivan

If you want to do it the cool way, use MonkeyRunner: http://www.reddit.com/r/Android/comments/1et8i3/i_modified_google_glass_home_camera_and_maps_apks/ca3kkgc

**Comment by limhenry** [comment]
BUT after a press the "ENTER", my setup app said "Failed to setup account" and "rebooting" then force close. WHY?

**Comment by Novo** [comment]
@Henry Same here ...

**Comment by Novo** [comment]
OK this was a problem with Android 4.0.3. Now I have 4.1.1 and it works.
